// CARDS
export const FETCH_TICKETS_START = 'FETCH_TICKETS_START'
export const FETCH_TICKETS_END_SUCCESS = 'FETCH_TICKETS_END_SUCCESS'
export const FETCH_TICKETS_END_FAIL = 'FETCH_TICKETS_END_FAIL'
export const REMOVE_TASK_START = 'REMOVE_TASK_START'
export const REMOVE_TASK_END_SUCCESS = 'REMOVE_TASK_START_END_SUCCESS'
export const REMOVE_TASK_END_FAIL = 'REMOVE_TASK_START_END_FAIL'