// CARDS
export const FETCH_TICKETS_START = 'FETCH_TICKETS_START'
export const FETCH_TICKETS_END_SUCCESS = 'FETCH_TICKETS_END_SUCCESS'
export const FETCH_TICKETS_END_FAIL = 'FETCH_TICKETS_END_FAIL'
export const FETCH_STATUSES_START = 'FETCH_STATUSES_START'
export const FETCH_STATUSES_END_SUCCESS = 'FETCH_STATUSES_END_SUCCESS'
export const FETCH_STATUSES_END_FAIL = 'FETCH_STATUSES_END_FAIL'
export const REMOVE_TASK_START = 'REMOVE_TASK_START'
export const REMOVE_TASK_END_SUCCESS = 'REMOVE_TASK_START_END_SUCCESS'
export const REMOVE_TASK_END_FAIL = 'REMOVE_TASK_START_END_FAIL'
export const CHANGE_TASK_STATUS_START = 'CHANGE_TASK_STATUS_START'
export const CHANGE_TASK_STATUS_END_SUCCESS = 'CHANGE_TASK_STATUS_END_SUCCESS'
export const CHANGE_TASK_STATUS_END_FAIL = 'CHANGE_TASK_STATUS_END_FAIL'
export const FETCH_ARCHIVE_TICKETS_START = 'FETCH_ARCHIVE_TICKETS_START'
export const FETCH_ARCHIVE_TICKETS_END_SUCCESS = 'FETCH_ARCHIVE_TICKETS_END_SUCCESS'
export const FETCH_ARCHIVE_TICKETS_END_FAIL = 'FETCH_ARCHIVE_TICKETS_END_FAIL'
// DND
export const TYPES = {
  CARD: 'card'
}